# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180424_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='main/static/main/images/categories'),
        ),
    ]
