# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180501_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='C:/media//categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='C:/media//products/'),
        ),
    ]
