# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180501_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('photo', models.FileField(upload_to='C:\\Users\\Moamen\\Desktop\\vmpub/media/impression/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='C:\\Users\\Moamen\\Desktop\\vmpub/media/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='C:\\Users\\Moamen\\Desktop\\vmpub/media/products/'),
        ),
    ]
