# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180506_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='C:\\Users\\Moamen\\Desktop\\vmpub/media/impression/')),
            ],
        ),
    ]
