# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.FileField(upload_to='C:\\Users\\Moamen\\Desktop\\vmpub/media/catalog/'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.FileField(upload_to='C:\\Users\\Moamen\\Desktop\\vmpub/media/product-photos/'),
        ),
    ]
